### ISSUE TITLE
Why use find in getOne methods if findOne can be used?

### ISSUE THREAD

**Issue by fedegomezdev** [Melt04/graphql-recipes#1]
https://github.com/Melt04/graphql-recipes/blob/a979922df5eaf55bc344ecc75736f0ae3716473f/tutorial-graphql/src/schema/resolvers/recipe.ts#L34

**Comment by Melt04** [comment]
Solucionado.

https://github.com/Melt04/graphql-recipes/blob/74835f5a4f20c23e6cdfd95953cbb0af14f3e2bd/tutorial-graphql/src/schema/resolvers/recipe.ts#L36-L38

También se modifico en otras partes del código donde era  correcto usar findOne
