### ISSUE TITLE
You can use the "update" method, imagine a entity with 50 columns

### ISSUE THREAD

**Issue by fedegomezdev** [Melt04/graphql-recipes#2]
https://github.com/Melt04/graphql-recipes/blob/a979922df5eaf55bc344ecc75736f0ae3716473f/tutorial-graphql/src/schema/resolvers/recipe.ts#L75

**Comment by Melt04** [comment]
Solucionado

https://github.com/Melt04/graphql-recipes/blob/74835f5a4f20c23e6cdfd95953cbb0af14f3e2bd/tutorial-graphql/src/schema/resolvers/recipe.ts#L73-L76
